# Generated by Django 5.1.4 on 2025-01-02 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Company')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Developer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Developer')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Platform',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Platform')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='VideoGame',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200, unique=True, verbose_name='Title')),
                ('year', models.IntegerField(verbose_name='Release Year')),
                ('description', models.TextField(verbose_name='Description')),
                ('date_scraped', models.DateTimeField(auto_now_add=True, verbose_name='Date Scraped')),
                ('companies', models.ManyToManyField(to='main.company', verbose_name='Companies')),
                ('developers', models.ManyToManyField(to='main.developer', verbose_name='Developers')),
                ('platforms', models.ManyToManyField(to='main.platform', verbose_name='Platforms')),
            ],
            options={
                'ordering': ('title',),
            },
        ),
    ]
