# Generated by Django 5.1.4 on 2025-01-03 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_company_name_alter_developer_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videogame',
            name='companies',
        ),
        migrations.RemoveField(
            model_name='videogame',
            name='developers',
        ),
        migrations.RemoveField(
            model_name='videogame',
            name='platforms',
        ),
        migrations.AddField(
            model_name='videogame',
            name='companies',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='videogame',
            name='developers',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='videogame',
            name='platforms',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
