# Generated by Django 5.1.4 on 2025-01-03 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_videogame_companies_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videogame',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
