# Generated by Django 5.1.4 on 2025-01-06 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_videogame_title'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VideoGame',
        ),
    ]
